variables:
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"

stages:
  - build-docker

image: node:16-bullseye-slim

build-docker:
  stage: build-docker
  image: quay.io/buildah/stable:v1.32
  script:
    - buildah build ./backstage -f Dockerfile-base -t backstage-base
    - buildah build ./backstage -t backstage:1.0
