variables:
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"

stages:
  - build-docker

image: node:16-bullseye-slim

build-docker:
  stage: build-docker
  image: quay.io/buildah/stable:v1.32
  variables:
    BUILDAH_FORMAT: docker
    STORAGE_DRIVER: vfs
  script:
    - buildah images
    - buildah build -f Dockerfile-base -t backstage-base ./backstage
    - buildah build -t backstage:1.0 ./backstage
    - buildah images
