version: "3"
services:
  backstage-app:
    build:
      context: backstage
    ports:
      - 7007:7007
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      AUTH_GITLAB_CLIENT_ID: ${AUTH_GITLAB_CLIENT_ID}
      AUTH_GITLAB_CLIENT_SECRET: ${AUTH_GITLAB_CLIENT_SECRET}
      AUTH_GITLAB_URL: ${AUTH_GITLAB_URL}
      GITLAB_HOSTNAME: ${GITLAB_HOSTNAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: backstage
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
