version: "3"
services:
  backstage-app:
    build:
      context: backstage
    ports:
      - 30003:7007
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      AUTH_GITLAB_CLIENT_ID: ${AUTH_GITLAB_CLIENT_ID}
      AUTH_GITLAB_CLIENT_SECRET: ${AUTH_GITLAB_CLIENT_SECRET}
      AUTH_GITLAB_URL: ${AUTH_GITLAB_URL}
      GITLAB_HOSTNAME: ${GITLAB_HOSTNAME}
      K8S_SVC_ACC_TOKEN: ${K8S_SVC_ACC_TOKEN}
      K8S_CONFIG_CA_DATA: ${K8S_CONFIG_CA_DATA}
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
