version: "3"
services:
  backstage-app:
    build:
      context: backstage
    ports:
      - 7007:7007
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
    depends_on:
      - postgres

  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: backstage
    volumes:
      - ./data:/var/lib/postgresql/data
