apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.name | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    github.com/project-slug: {{cookiecutter.destination.owner + "/" + cookiecutter.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
