apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-envs
data:
  POSTGRES_HOST: backstage-db
  POSTGRES_PORT: "5432"
  AUTH_GITLAB_URL: https://gitlab.com
  GITLAB_HOSTNAME: gitlab.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-db
spec:
  selector:
    matchLabels:
      app: backstage-db
  template:
    metadata:
      labels:
        app: backstage-db
    spec:
      containers:
        - name: backstage-db
          image: postgres:15-bullseye
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-db-secret
                  key: POSTGRES_USER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-db-adminer
spec:
  selector:
    matchLabels:
      app: backstage-db-adminer
  template:
    metadata:
      labels:
        app: backstage-db-adminer
    spec:
      containers:
        - name: backstage-db-adminer
          image: adminer
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-app
  labels:
    backstage.io/kubernetes-id: backstage-app
spec:
  selector:
    matchLabels:
      app: backstage-app
  template:
    metadata:
      labels:
        app: backstage-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backstage-app
          image: registry.gitlab.com/ctgjdw1/backstage-app
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 7007
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: backstage-app-envs
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: backstage-app-envs
                  key: POSTGRES_PORT
            - name: GITLAB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backstage-app-envs
                  key: GITLAB_HOSTNAME
            - name: AUTH_GITLAB_URL
              valueFrom:
                configMapKeyRef:
                  name: backstage-app-envs
                  key: AUTH_GITLAB_URL
            - name: AUTH_GITLAB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backstage-app-secret
                  key: AUTH_GITLAB_CLIENT_ID
            - name: AUTH_GITLAB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backstage-app-secret
                  key: AUTH_GITLAB_CLIENT_SECRET
            - name: K8S_SVC_ACC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-app-secret
                  key: K8S_SVC_ACC_TOKEN
            - name: K8S_CONFIG_CA_DATA
              valueFrom:
                secretKeyRef:
                  name: backstage-app-secret
                  key: K8S_CONFIG_CA_DATA
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-db
spec:
  type: NodePort
  selector:
    app: backstage-db
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-db-adminer
spec:
  type: NodePort
  selector:
    app: backstage-db-adminer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-app
  labels:
    backstage.io/kubernetes-id: backstage-app
spec:
  type: NodePort
  selector:
    app: backstage-app
  ports:
    - port: 7007
      targetPort: 7007
      nodePort: 30003
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-kube
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-k8s-read-only
subjects:
  - kind: ServiceAccount
    name: backstage-kube
    namespace: default
roleRef:
  kind: ClusterRole
  name: backstage-read-only
  apiGroup: rbac.authorization.k8s.io
