apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-envs
  labels:
    backstage.io/kubernetes-id: backstage-app
data:
  POSTGRES_HOST: backstage-db
  POSTGRES_PORT: "5432"
  AUTH_GITLAB_URL: https://gitlab.com
  GITLAB_HOSTNAME: gitlab.com
  BACKSTAGE_APP_URL: http://localhost:30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-db
  labels:
    backstage.io/kubernetes-id: backstage-app
spec:
  selector:
    matchLabels:
      app: backstage-db
  template:
    metadata:
      labels:
        app: backstage-db
        backstage.io/kubernetes-id: backstage-app
    spec:
      volumes:
        - name: backstage-db-vol
          hostPath:
            path: /run/desktop/mnt/host/c/KubeData/backstage-db
            type: Directory
      containers:
        - name: backstage-db
          image: postgres:15-bullseye
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: backstage-db-vol
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-db-secret
                  key: POSTGRES_USER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-db-adminer
spec:
  selector:
    matchLabels:
      app: backstage-db-adminer
  template:
    metadata:
      labels:
        app: backstage-db-adminer
    spec:
      containers:
        - name: backstage-db-adminer
          image: adminer
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-app
  labels:
    backstage.io/kubernetes-id: backstage-app
spec:
  selector:
    matchLabels:
      app: backstage-app
  template:
    metadata:
      labels:
        app: backstage-app
        backstage.io/kubernetes-id: backstage-app
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: init-db
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup backstage-db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for db; sleep 2; done",
            ]
      containers:
        - name: backstage-app
          image: registry.gitlab.com/ctgjdw1/backstage-app
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 7007
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: backstage-app-envs
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: backstage-app-envs
                  key: POSTGRES_PORT
            - name: GITLAB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backstage-app-envs
                  key: GITLAB_HOSTNAME
            - name: AUTH_GITLAB_URL
              valueFrom:
                configMapKeyRef:
                  name: backstage-app-envs
                  key: AUTH_GITLAB_URL
            - name: AUTH_GITLAB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backstage-app-secret
                  key: AUTH_GITLAB_CLIENT_ID
            - name: AUTH_GITLAB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backstage-app-secret
                  key: AUTH_GITLAB_CLIENT_SECRET
            - name: K8S_SVC_ACC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-app-secret
                  key: K8S_SVC_ACC_TOKEN
            - name: K8S_CONFIG_CA_DATA
              valueFrom:
                secretKeyRef:
                  name: backstage-app-secret
                  key: K8S_CONFIG_CA_DATA
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-db
  labels:
    backstage.io/kubernetes-id: backstage-app
spec:
  type: NodePort
  selector:
    app: backstage-db
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-db-adminer
spec:
  type: NodePort
  selector:
    app: backstage-db-adminer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-app
  labels:
    backstage.io/kubernetes-id: backstage-app
spec:
  type: NodePort
  selector:
    app: backstage-app
  ports:
    - port: 7007
      targetPort: 7007
      nodePort: 30003
---

